### ISSUE TITLE
Tags for version bumps

### ISSUE THREAD

**Issue by inconstante** [SUSE/libpulp#220]
Hi,

Would it be possible to tag the commits that bump autoconf version? The last time it was done, libpulp was in version 0.2.2 (for reference: [bump](https://github.com/SUSE/libpulp/commit/a277e78b1a1f5f659b4f8aa87c5586331c17be76) and [tag](https://github.com/SUSE/libpulp/releases/tag/0.2.2))

Cheers!

**Comment by giulianobelinassi** [comment]
Thanks! I have updated the current bump to include tags as well :)
