### ISSUE TITLE
No access to TLS variables in target libraries

### ISSUE THREAD

**Issue by inconstante** [SUSE/libpulp#31]
Pull request #19 adds support for live patches that require access to unexported variables in the target library. However, that only works for variables that are shared among all threads of the target process. When the variable resides in thread-local storage, that doesn't work. This issue is here to remind us that access to unexported thread-local variables is currently not supported by Libpulp.

**Comment by giulianobelinassi** [comment]
Fixed in c76a60a740c5c099de89f78ba992dcf389f98527
