### ISSUE TITLE
No tests for build id mismatch

### ISSUE THREAD

**Issue by inconstante** [SUSE/libpulp#39]
As discussed in a pull request [review](https://github.com/SUSE/libpulp/pull/34#pullrequestreview-732258300), a live patch is only applied when the build ids of the live patch object and target library match the build ids recorded in the metadata file. However, all test cases in the test suite have matching build ids. A new test case with a deliberate mismatch should be added to the test suite so that the respective code path gets some coverage.

**Comment by giulianobelinassi** [comment]
This was fixed in PR #44
