### ISSUE TITLE
About ptrace freeze time

### ISSUE THREAD

**Issue by qztangtou** [SUSE/libpulp#8]
Since ptrace causes downtime when target threads are freezed.  How much downtime would be for libpulp?

**Comment by inconstante** [comment]
It depends on several factors, such as on the clock speed and on how you measure it.

For instance, if I patch the trigger tool with the following diff:

```
diff --git a/tools/trigger.c b/tools/trigger.c
index 47d5cce3..df841d0c 100644
--- a/tools/trigger.c
+++ b/tools/trigger.c
@@ -23,11 +23,13 @@
 #include <errno.h>
 #include <fcntl.h>
 #include <link.h>
+#include <locale.h>
 #include <stddef.h>
 #include <stdio.h>
 #include <stdlib.h>
 #include <string.h>
 #include <sys/user.h>
+#include <time.h>
 #include <unistd.h>
 
 #include "introspection.h"
@@ -86,6 +88,8 @@ main(int argc, char **argv)
    * i.e. if glibc internal locks for calloc and dlopen are free,
    * before actually applying it.
    */
+  struct timespec time1, time2;
+  clock_gettime(CLOCK_MONOTONIC, &time1);
   retry = 100;
   while (retry) {
     retry--;
@@ -115,6 +119,11 @@ main(int argc, char **argv)
       return 9;
     usleep(1000);
   }
+  clock_gettime(CLOCK_MONOTONIC, &time2);
+  setlocale(LC_ALL, "de_DE.UTF-8");
+  WARN("Elapsed time: %'lu ns.",
+       (  ((time2.tv_sec  - time1.tv_sec) * (time_t)1000000000)
+        + ((time2.tv_nsec - time1.tv_nsec))));
 
   if (ret)
     return 1;
```

I get the following numbers:
```
$ make check TESTS=parameters
$ grep Elapsed tests/parameters.log 
ulp: Elapsed time: 21.741.109 ns.
```

With more contention, such as on the test case for deadlock (use pull request #9, otherwise you might hit deadlocks and won't see any numbers), these numbers might be higher (specially if the trigger tool has to retry (detach and re-attach) multiple times):
```
$ make check TESTS=deadlock
$ grep Elapsed tests/deadlock.log
ulp: Elapsed time: 44.917.495 ns.
ulp: Elapsed time: 44.612.503 ns.
ulp: Elapsed time: 53.553.097 ns.
ulp: Elapsed time: 93.005.234 ns.
ulp: Elapsed time: 45.923.041 ns.
ulp: Elapsed time: 28.296.859 ns.
ulp: Elapsed time: 26.917.526 ns.
ulp: Elapsed time: 26.873.808 ns.
ulp: Elapsed time: 48.545.761 ns.
ulp: Elapsed time: 26.899.467 ns.
ulp: Elapsed time: 49.184.203 ns.
ulp: Elapsed time: 47.800.179 ns.
ulp: Elapsed time: 131.343.933 ns.
ulp: Elapsed time: 106.174.299 ns.
ulp: Elapsed time: 210.488.471 ns.
ulp: Elapsed time: 49.465.272 ns.
ulp: Elapsed time: 47.707.798 ns.
ulp: Elapsed time: 48.852.941 ns.
ulp: Elapsed time: 66.743.798 ns.
ulp: Elapsed time: 111.049.653 ns.
ulp: Elapsed time: 47.590.648 ns.
ulp: Elapsed time: 26.789.362 ns.
ulp: Elapsed time: 66.909.031 ns.
ulp: Elapsed time: 26.832.537 ns.
ulp: Elapsed time: 86.902.299 ns.
ulp: Elapsed time: 53.869.808 ns.
ulp: Elapsed time: 170.445.960 ns.
ulp: Elapsed time: 106.479.754 ns.
ulp: Elapsed time: 115.399.849 ns.
ulp: Elapsed time: 111.808.721 ns.
ulp: Elapsed time: 128.477.159 ns.
ulp: Elapsed time: 56.290.272 ns.
```

Cheers,
Gabriel

**Comment by qztangtou** [comment]
> It depends on several factors, such as on the clock speed and on how you measure it.
> 
> For instance, if I patch the trigger tool with the following diff:
> 
> ```
> diff --git a/tools/trigger.c b/tools/trigger.c
> index 47d5cce3..df841d0c 100644
> --- a/tools/trigger.c
> +++ b/tools/trigger.c
> @@ -23,11 +23,13 @@
>  #include <errno.h>
>  #include <fcntl.h>
>  #include <link.h>
> +#include <locale.h>
>  #include <stddef.h>
>  #include <stdio.h>
>  #include <stdlib.h>
>  #include <string.h>
>  #include <sys/user.h>
> +#include <time.h>
>  #include <unistd.h>
>  
>  #include "introspection.h"
> @@ -86,6 +88,8 @@ main(int argc, char **argv)
>     * i.e. if glibc internal locks for calloc and dlopen are free,
>     * before actually applying it.
>     */
> +  struct timespec time1, time2;
> +  clock_gettime(CLOCK_MONOTONIC, &time1);
>    retry = 100;
>    while (retry) {
>      retry--;
> @@ -115,6 +119,11 @@ main(int argc, char **argv)
>        return 9;
>      usleep(1000);
>    }
> +  clock_gettime(CLOCK_MONOTONIC, &time2);
> +  setlocale(LC_ALL, "de_DE.UTF-8");
> +  WARN("Elapsed time: %'lu ns.",
> +       (  ((time2.tv_sec  - time1.tv_sec) * (time_t)1000000000)
> +        + ((time2.tv_nsec - time1.tv_nsec))));
>  
>    if (ret)
>      return 1;
> ```
> 
> I get the following numbers:
> 
> ```
> $ make check TESTS=parameters
> $ grep Elapsed tests/parameters.log 
> ulp: Elapsed time: 21.741.109 ns.
> ```
> 
> With more contention, such as on the test case for deadlock (use pull request #9, otherwise you might hit deadlocks and won't see any numbers), these numbers might be higher (specially if the trigger tool has to retry (detach and re-attach) multiple times):
> 
> ```
> $ make check TESTS=deadlock
> $ grep Elapsed tests/deadlock.log
> ulp: Elapsed time: 44.917.495 ns.
> ulp: Elapsed time: 44.612.503 ns.
> ulp: Elapsed time: 53.553.097 ns.
> ulp: Elapsed time: 93.005.234 ns.
> ulp: Elapsed time: 45.923.041 ns.
> ulp: Elapsed time: 28.296.859 ns.
> ulp: Elapsed time: 26.917.526 ns.
> ulp: Elapsed time: 26.873.808 ns.
> ulp: Elapsed time: 48.545.761 ns.
> ulp: Elapsed time: 26.899.467 ns.
> ulp: Elapsed time: 49.184.203 ns.
> ulp: Elapsed time: 47.800.179 ns.
> ulp: Elapsed time: 131.343.933 ns.
> ulp: Elapsed time: 106.174.299 ns.
> ulp: Elapsed time: 210.488.471 ns.
> ulp: Elapsed time: 49.465.272 ns.
> ulp: Elapsed time: 47.707.798 ns.
> ulp: Elapsed time: 48.852.941 ns.
> ulp: Elapsed time: 66.743.798 ns.
> ulp: Elapsed time: 111.049.653 ns.
> ulp: Elapsed time: 47.590.648 ns.
> ulp: Elapsed time: 26.789.362 ns.
> ulp: Elapsed time: 66.909.031 ns.
> ulp: Elapsed time: 26.832.537 ns.
> ulp: Elapsed time: 86.902.299 ns.
> ulp: Elapsed time: 53.869.808 ns.
> ulp: Elapsed time: 170.445.960 ns.
> ulp: Elapsed time: 106.479.754 ns.
> ulp: Elapsed time: 115.399.849 ns.
> ulp: Elapsed time: 111.808.721 ns.
> ulp: Elapsed time: 128.477.159 ns.
> ulp: Elapsed time: 56.290.272 ns.
> ```
> 
> Cheers,
> Gabriel

Hi, Gabriel, Thank you for your reply.
So, the libpulp downtime is in the scale of millisecond. That's reasonable because it would be inevitable if we hijack target threads through ptrace() rather than kernel livepatch by "curing itself":)

**Comment by a-gavin** [comment]
This issue has been stale for several months. I suggest closing

**Comment by inconstante** [comment]
Indeed, thanks for the reminder.
